//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainYourBrain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainYourBrain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;рбет
        ///&apos;рт
        ///&apos;рѓа
        ///`рбел
        ///`рбет
        ///`рбетен
        ///`рбет
        ///`рбетен
        ///`рбетник
        ///`рбетен
        ///`рбетница
        ///`рбетник
        ///`рбетница
        ///`рбетник
        ///`рбетница
        ///`рбетник
        ///`рбетница
        ///`рбетник
        ///`рбетница
        ///`рбетник
        ///`рбетен
        ///`рбет
        ///`рбол
        ///`рвајчи
        ///`рвајчејќи
        ///`рвајчење
        ///`рвајчи
        ///`рвеник
        ///`рга
        ///`ргало
        ///`рга
        ///`ргало
        ///`рга
        ///`ргач
        ///`рга
        ///`ргајќи
        ///`ргање
        ///`ргне
        ///`ргнува
        ///`ргнувајќи
        ///`ргнување
        ///`ргнува
        ///`рдоква
        ///`рдоквен
        ///`рдоква
        ///`рж
        ///`ржи
        ///`ржан
        ///`ржаник
        ///`ржан
        ///`ржаница
        ///`ржаник
        ///`ржаница
        ///`ржаник
        ///`ржаница
        ///`ржаник
        ///`ржаница
        ///`ржаник
        ///`ржаница [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string baza {
            get {
                return ResourceManager.GetString("baza", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream click {
            get {
                return ResourceManager.GetStream("click", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream greska {
            get {
                return ResourceManager.GetStream("greska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marija	20
        ///Darinka	30
        ///Danche	50.
        /// </summary>
        internal static string highscore {
            get {
                return ResourceManager.GetString("highscore", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Logo_FINKI_MK {
            get {
                object obj = ResourceManager.GetObject("Logo_FINKI_MK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream lose {
            get {
                return ResourceManager.GetStream("lose", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap slika1 {
            get {
                object obj = ResourceManager.GetObject("slika1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap slika2 {
            get {
                object obj = ResourceManager.GetObject("slika2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap slika3 {
            get {
                object obj = ResourceManager.GetObject("slika3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap slika4 {
            get {
                object obj = ResourceManager.GetObject("slika4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap slika5 {
            get {
                object obj = ResourceManager.GetObject("slika5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap slika6 {
            get {
                object obj = ResourceManager.GetObject("slika6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spade {
            get {
                object obj = ResourceManager.GetObject("Spade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splash_back {
            get {
                object obj = ResourceManager.GetObject("splash_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap symbol_48940_640 {
            get {
                object obj = ResourceManager.GetObject("symbol_48940_640", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candy
        ///#F5DEB3$#CD5C5C$#FFFFFF
        ///Batman
        ///#999999$#4B66B8$#FFFFFF.
        /// </summary>
        internal static string temi {
            get {
                return ResourceManager.GetString("temi", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream tocno {
            get {
                return ResourceManager.GetStream("tocno", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream win {
            get {
                return ResourceManager.GetStream("win", resourceCulture);
            }
        }
    }
}
